adding bbox to solr managed schema and mongo init
FREVA-CLINT/freva-service-config pull request #27
Opened 2024-11-13 09:47 UTC by mo-dkrz

To incorporate the new `bbox` field into Solr for generating a metadata catalog from the Freva NextGen databrowser, we need to first define the field here. Once defined, this parameter will be accessible for metadata generation. Additionally, I’ve updated the `bbox` entry in the `mono` initialization file

2024-11-13 09:53 UTC, antarcticrainforest requested changes
I think, it would be better if we split this into lons and lats. From a practical point of view users might want to look for data that between 30 S and 30 N (tropics) but are not interested in any longitude constraints (global tropics).

I cannot say much about the BBoxField in solr, @Karinon do you have any insights?

2024-11-13 09:54 UTC, antarcticrainforest commented
But of course, we could handle the bbox construction from the API server side.

2024-11-13 10:23 UTC, mo-dkrz commented
> I think, it would be better if we split this into lons and lats. From a practical point of view users might want to look for data that between 30 S and 30 N (tropics) but are not interested in any longitude constraints (global tropics).
@antarcticrainforest 
ahh I forgot to put it in the draft, I'm not done with this PR yet. could you please give me more time since I have a map for this in my head. Still two PRs are left, one in `data-crawler` and one in `freva-web`. 
when all are done i ask you for the review, thanks

2024-11-13 17:50 UTC, mo-dkrz commented
@antarcticrainforest 

do you still believe in this:
> I think, it would be better if we split this into lons and lats. From a practical point of view users might want to look for data that between 30 S and 30 N (tropics) but are not interested in any longitude constraints (global tropics).

It's the standard way of using bbox in Solr, please let me know if you are not happy with this
@Karinon any idea?

2024-11-13 17:50 UTC, mo-dkrz commented
@antarcticrainforest when it's done, I'm going to open another PR in freva and update the freva-service submodule there

2024-11-14 07:06 UTC, Karinon commented
I haven used the `BBoxField` in Solr before and I don't know any specifics about it. In WDCC I am using the following schema for my BoundingBoxes:

```
  <fieldType name="location_rpt" class="solr.SpatialRecursivePrefixTreeFieldType" normWrapLongitude="true"
             geo="true" distErrPct="0.025" maxDistErr="0.001" distanceUnits="degrees" />

   <field name="geo" type="location_rpt" multiValued="true" indexed="true" stored="true"/>
```

Inside a Document it looks like the following:

```
        "geo":["ENVELOPE(-180.00, 180.00, 90.00,-90.00)"],
```

After that, you can essentially query it like the temporal coverage:

```
fq='geo:"Contains(ENVELOPE(-19.4,66.8,39.1,-39.4))"'
```

Where `Contains` can be replaced by other operators like `Intersects` and `Within`

2024-11-14 07:11 UTC, Karinon commented
Regarding the question about splitting it into lots and lats (I skipped it at first reading):

I wouldn't do it as I would like to let Solr do the work and not implement something on my own.

The very same goal can be achieved by a query like fq='geo:"Contains(WITHIN(-180.00, 180.00,30,30.0))"', or if `WITHIN` is too restrictive also with `INTERSECTS`

2024-11-15 08:06 UTC, mo-dkrz commented
Thanks @Karinon like always, it was on time and constructive. Because in another MR we were discussing to find a way to handle curvilinear coords which are not rectangular. I don't merge this until I see what's gonna happen during development  of other components cause we might change a bit of stuff here

2024-11-25 11:07 UTC, mo-dkrz commented
@Karinon @antarcticrainforest since i need these changes on the main branch for producing `freva` docker image, I wanted merge this. Do u have any other comment that I have to change here?

2024-11-25 15:03 UTC, antarcticrainforest approved these changes
LGTM!

2024-11-25 15:07 UTC, merged